(load "./Sesler_Walsh_Interpreter.scm")

(define runtest
  (lambda (file class result)
    (display file)
    (display ": ")
    (if (eq? (interpret file class) result)
      (display "Passed")
      (display "Failed"))
    (newline)))

(runtest "tests/test1.x" "A" 10)
(runtest "tests/test2.x" "A" 20)
(runtest "tests/test3.x" "A" 30)
(runtest "tests/test4.x" "A" 30)
(runtest "tests/test5.x" "A" 30)
(runtest "tests/test5.x" "B" 510)
(runtest "tests/test6.x" "A" 30)
(runtest "tests/test6.x" "B" 530)
(runtest "tests/test7.x" "A" 105)
(runtest "tests/test7.x" "B" 1155)
(runtest "tests/test8.x" "B" 615)
; supposed to error
;(runtest "tests/test9.x" "B" -1)
(runtest "tests/test9.x" "C" 4321)
(runtest "tests/test10.x" "Square" 400)
(runtest "tests/test11.x" "A" 530)
(runtest "tests/test12/x" "B" 66)
