(load "Sesler_Walsh_Interpreter.scm")

(define runtest
  (lambda (file result)
    (display file)
    (display ": ")
    (if (eq? (interpret file) result)
      (display "Passed")
      (display "Failed"))
    (newline)))

(runtest "tests/test1.x" 150)
(runtest "tests/test2.x" -4)
(runtest "tests/test3.x" 10)
(runtest "tests/test4.x" 16)
(runtest "tests/test5.x" 220)
(runtest "tests/test6.x" 5)
(runtest "tests/test7.x" 6)
(runtest "tests/test8.x" 10)
(runtest "tests/test9.x" 5)
(runtest "tests/test10.x" -39)
; test11, test12, test13, and test14 should error
(runtest "tests/test15.x" 'true)
(runtest "tests/test16.x" 100)
(runtest "tests/test17.x" 'false)
(runtest "tests/test18.x" 'true)
(runtest "tests/test19.x" 30)
(runtest "tests/test20.x" 11)
(runtest "tests/test21.x" 1106)
(runtest "tests/test22.x" 12)
(runtest "tests/test23.x" 16)
(runtest "tests/test24.x" 72)

(runtest "tests/test25.x" 5)
(runtest "tests/test26.x" 7)
(runtest "tests/test27.x" 17)
(runtest "tests/test28.x" 12)
(runtest "tests/test29.x" 6)
(runtest "tests/test30.x" 10)
(runtest "tests/test31.x" 11)
(runtest "tests/test32.x" 6)
(runtest "tests/test33.x" 5)
